prac4.out: main.o node.o table.o
	g++ main.o node.o table.o -o prac4.out

main.o: main.cpp
	g++ -c main.cpp

node.o: node.cpp
	g++ -c node.cpp

table.o: table.cpp
	g++ -c table.cpp

run:
	./prac4.out

clean:
	rm*.o prac4



